name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (with tests) and tag (loaded locally)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hashcheck:ci-${{ github.sha }}

      - name: Run container quick check
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/hashcheck:ci-${{ github.sha }} --text "hello" --json

      - name: Re-tag as latest and sha
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/hashcheck:ci-${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/hashcheck:sha-${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/hashcheck:ci-${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/hashcheck:latest

      - name: Push images (main only)
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hashcheck:sha-${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hashcheck:latest
